### ISSUE TITLE
Username or password wrong.

### ISSUE THREAD

**Issue by wanglong167** [TossShinHwa/CMS#8]
Username or password wrong.

**Comment by wanglong167** [comment]
admin 123  是错的

**Comment by TossShinHwa** [comment]
@wanglong167 , 你需要取消下面选中行的注释来初始化数据:
https://github.com/TossShinHwa/CMS/blob/master/server/server.coffee#L35

用户相关的测试数据位于:
https://github.com/TossShinHwa/CMS/blob/master/server/bootstrap/test-data/system/user.json

不过请记住, 这个项目的演示意义大于实用价值, 由于演示如何使用 Angular + Bootstrap + NodeJS + node-odata 来构建项目. 感谢关注.

**Comment by wanglong167** [comment]
Schema hasn't been registered for model "User".
这是什么原因？ 刚不初始化数据还能看到登录。。

**Comment by TossShinHwa** [comment]
Sorry, 上次修改数据结构增加了支持国际化的一些内容并且调整了插入的方式, 没有同步修改初始化这边的数据. 我刚刚已经[修复了](https://github.com/TossShinHwa/CMS/commit/f2ca397c3e8e93d5e3ab3541597b9b1e3f875954)这个问题, 请获取下最新版本再试一次.

**Comment by wanglong167** [comment]
嗯 可以了
