### ISSUE TITLE
Not building...

### ISSUE THREAD

**Issue by stdex** [TossShinHwa/CMS#9]
pc:~/ncms/CMS$ grunt

> Running "build" task
> Running "coffeelint:app" (coffeelint) task
> client/public/app/_framework/framework-HeadCtrl.coffee
> ⚠  line 11  Comprehensions must have parentheses around them
> ⚠ 1 warning
> 
> client/public/app/index/index.coffee
> ✖ line 15  Line contains a trailing semicolon
> ✖ 1 error
> 
> client/public/common/directives/oDataPager.coffee
> ✖ line 16  Line contains a trailing semicolon
> ✖ 1 error
> 
> server/odata/system/user.coffee
> ⚠  line 20  Debugger statements will cause warnings  found 'DEBUGGER'
> ⚠  line 22  Debugger statements will cause warnings  found 'DEBUGGER'
> ⚠ 2 warnings
> 
> Warning: Task "coffeelint:app" failed. Use --force to continue.
> Aborted due to warnings.

pc:~/ncms/CMS$ grunt --force
> Running "build" task
> Running "coffeelint:app" (coffeelint) task
> 
> client/public/app/_framework/framework-HeadCtrl.coffee
> ⚠ line 11  Comprehensions must have parentheses around them
> ⚠ 1 warning
> 
> client/public/app/index/index.coffee
> ✖ line 15  Line contains a trailing semicolon
> ✖ 1 error
> 
> client/public/common/directives/oDataPager.coffee
> ✖ line 16  Line contains a trailing semicolon
> ✖ 1 error
> 
> server/odata/system/user.coffee
> ⚠  line 20  Debugger statements will cause warnings  found 'DEBUGGER'
> ⚠  line 22  Debugger statements will cause warnings  found 'DEBUGGER'
> ⚠ 2 warnings
> 
> Warning: Task "coffeelint:app" failed. Used --force, continuing.
> 
> ...
> Nodemon start
> ...
> events.js:72
>         throw er; // Unhandled 'error' event
>               ^
> Error: failed to connect to [localhost:27017]
>   at [object Object].<anonymous> (/ncms/CMS/node_modules/node-odata/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:549:74)
>   at [object Object].EventEmitter.emit (events.js:106:17)
>   at [object Object].<anonymous> (/ncms/CMS/node_modules/node-odata/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:> 150:15)
>   at [object Object].EventEmitter.emit (events.js:98:17)
>   at Socket.<anonymous> (/ncms/CMS/node_modules/node-odata/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:533:1> 0)
>   at Socket.EventEmitter.emit (events.js:95:17)
>   at net.js:441:14
>   at process._tickDomainCallback (node.js:459:13)
> 
> [nodemon] app crashed - waiting for file changes before starting...

node --version
> v0.10.25

bower --version
> 1.4.1

grunt --version
> grunt-cli v0.1.13
> grunt v0.4.5

**Comment by TossShinHwa** [comment]
```
Error: failed to connect to [localhost:27017]
```

You should keep mongoDB run at localhost:27017.

Thank you.
